## Data manipulation and data analysis
pandas is widely used for data manipulation and data analysis in Python. Data manipulation means modifying or transforming the dataset (adding, removing, filtering, or updating data), while data analysis means extracting useful insights such as averages, counts, or patterns from the data.

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('sales_data.csv')  # this sales data have some missing values in it 
# fetch the first 5 rows
df.head(5)

         Date Category  Value   Product  Sales Region
0  2023-02-01        A   45.0  Product1  650.0  North
1  2023-02-02        B   32.0  Product2  720.0   West
2  2023-02-03        C    NaN  Product3  580.0  South
3  2023-02-04        A   28.0  Product1  490.0   East
4  2023-02-05        B   60.0  Product2    NaN   West

In [4]:
## last 5 rows
df.tail(5)

          Date Category  Value   Product  Sales Region
25  2023-02-26        B   57.0  Product2  710.0   East
26  2023-02-27        C    NaN  Product3  560.0  North
27  2023-02-28        A   66.0  Product1  870.0  South
28  2023-03-01        B   52.0  Product2  690.0    NaN
29  2023-03-02        C   79.0  Product3  940.0   West

In [5]:
df.describe()   # it will give you all the statistical info of the data and it is only for the numerical columns and not for the categorical columns

           Value        Sales
count  23.000000    26.000000
mean   56.347826   695.769231
std    17.245839   149.028134
min    28.000000   450.000000
25%    43.000000   582.500000
50%    55.000000   685.000000
75%    67.000000   797.500000
max    90.000000  1000.000000

# handling missing values

In [6]:
# Handling Missing Values
df.isnull()  # Check where values are missing and gives true for a missing value

     Date  Category  Value  Product  Sales  Region
0   False     False  False    False  False   False
1   False     False  False    False  False   False
2   False     False   True    False  False   False
3   False     False  False    False  False   False
4   False     False  False    False   True   False
5   False     False  False    False  False    True
6   False     False   True    False  False   False
7   False     False  False    False  False   False
8   False     False  False     True  False   False
9   False     False  False    False  False   False
10  False     False   True    False  False   False
11  False     False  False    False  False   False
12  False     False  False    False   True   False
13  False     False  False    False  False   False
14  False     False   True    False  False   False
15  False     False  False    False  False   False
16  False     False  False    False  False   False
17  False     False  False    False   True   False
18  False     False   True    False  False   False
19  False     False  False    False  False   False
20  False     False  False    False  False   False
21  False     False  False    False   True   False
22  False     False   True    False  False   False
23  False     False  False    False  False   False
24  False     False  False     True  False   False
25  False     False  False    False  False   False
26  False     False   True    False  False   False
27  False     False  False    False  False   False
28  False     False  False    False  False    True
29  False     False  False    False  False   False

In [7]:
df.isnull().sum() # Count missing values in each column

Date        0
Category    0
Value       7
Product     2
Sales       4
Region      2
dtype: int64

In [8]:
df.isnull().any(axis=1) # Check each row(record) and If any column has missing value → True

0     False
1     False
2      True
3     False
4      True
5      True
6      True
7     False
8      True
9     False
10     True
11    False
12     True
13    False
14     True
15    False
16    False
17     True
18     True
19    False
20    False
21     True
22     True
23    False
24     True
25    False
26     True
27    False
28     True
29    False
dtype: bool

In [9]:
df.isnull().any() # here it takes bydefault axis = 0 and check each column wise

Date        False
Category    False
Value        True
Product      True
Sales        True
Region       True
dtype: bool

In [10]:
df.fillna(0) # replace all the missing values with 0
# usually we make an another copy of the data and then apply the changes like this
df_filled = df.fillna(0)  # make copy so that the original data should never be hampered
# generally we don't fill the missing values with the 0s

In [11]:
# filling the missing values with the mean of the column
df['Sales'].fillna(df['Sales'].mean()) # filling the missing values of the sales column with the mean of the sales column

df['Sales_fillNA'] = df['Sales'].fillna(df['Sales'].mean()) #Creates a new column called Sales_fillNA.This column contains the Sales values but with missing values replaced by the mean. So the original column stays unchanged.

In [12]:
# Rename the column
df = df.rename(columns={'Date' : 'Sale Date'})
df.head()

    Sale Date Category  Value   Product  Sales Region  Sales_fillNA
0  2023-02-01        A   45.0  Product1  650.0  North    650.000000
1  2023-02-02        B   32.0  Product2  720.0   West    720.000000
2  2023-02-03        C    NaN  Product3  580.0  South    580.000000
3  2023-02-04        A   28.0  Product1  490.0   East    490.000000
4  2023-02-05        B   60.0  Product2    NaN   West    695.769231

In [ ]:
# Change the data types
df['New_Vlaues'] = df['Value'].astype(float)  # a new column of float values are created 
df.head()

,Sale Date,Category,Value,Product,Sales,Region,Sales_fillNA,New_Vlaues
0,2023-02-01,A,45.0,Product1,650.0,North,650.000000,45.0
1,2023-02-02,B,32.0,Product2,720.0,West,720.000000,32.0
2,2023-02-03,C,NaN,Product3,580.0,South,580.000000,NaN
3,2023-02-04,A,28.0,Product1,490.0,East,490.000000,28.0
4,2023-02-05,B,60.0,Product2,NaN,West,695.769231,60.0

In [ ]:
# apply a function to a column
# df['column_name'].apply(function)
df['New Value'] = df['Value'].apply(lambda x : x*2) # applied the lambda function to the col
df.head()

,Sale Date,Category,Value,Product,Sales,Region,Sales_fillNA,New_Vlaues,New Value
0,2023-02-01,A,45.0,Product1,650.0,North,650.000000,45.0,90.0
1,2023-02-02,B,32.0,Product2,720.0,West,720.000000,32.0,64.0
2,2023-02-03,C,NaN,Product3,580.0,South,580.000000,NaN,NaN
3,2023-02-04,A,28.0,Product1,490.0,East,490.000000,28.0,56.0
4,2023-02-05,B,60.0,Product2,NaN,West,695.769231,60.0,120.0

In [ ]:
# Data Aggregation and Grouping
grouped_mean = df.groupby('Product')['Value'].mean() # This groups the dataframe by the Product column and then for each product type show the mean of the value 
print(grouped_mean)

Product
Product1    60.375000
Product2    51.428571
Product3    62.000000
Name: Value, dtype: float64

In [ ]:
grouped_data = df.groupby(['Product','Region'])['Value'].sum() # grouping of the data by using 2 columns and then get the sum of value columns
print(grouped_data)

Product   Region
Product1  East       76.0
          North      45.0
          South     299.0
          West       63.0
Product2  East      144.0
          North       0.0
          South      72.0
          West       92.0
Product3  East       68.0
          North       0.0
          South      54.0
          West      175.0
Name: Value, dtype: float64

In [17]:
grouped_data = df.groupby(['Product','Region'])['Value'].mean()
print(grouped_data)

Product   Region
Product1  East      38.000000
          North     45.000000
          South     74.750000
          West      63.000000
Product2  East      48.000000
          North           NaN
          South     72.000000
          West      46.000000
Product3  East      68.000000
          North           NaN
          South     54.000000
          West      58.333333
Name: Value, dtype: float64

In [ ]:
# Multiple aggregation functions , applying multiple aggregate functions to a column or colums
grouped_agg = df.groupby('Region')['Value'].agg(['mean','sum','count'])
print(grouped_agg)

             mean    sum  count
Region
East    48.000000  288.0      6
North   45.000000   45.0      1
South   70.833333  425.0      6
West    51.375000  411.0      8

NOTE:- Whatever we are doing in SQL , we can do it in Python

## Merging and joining DataFrames

In Pandas, merging and joining are used to combine multiple DataFrames into one.

This is very common in data analysis and ML preprocessing.

Think of it like joining tables in SQL.

merge() combines DataFrames using a common column (key).

In [27]:
# Creating sample data frames and here the key and the values are the columns
df1 = pd.DataFrame({'key' : ['A','B','C'] , 'Values1' : [1,2,3]}) 
df2 = pd.DataFrame({'key' : ['A','B','D'] , 'Values2' : [4,5,6]})

In [29]:
df1

  key  Values1
0   A        1
1   B        2
2   C        3

In [30]:
df2

  key  Values2
0   A        4
1   B        5
2   D        6

In [ ]:
## Merge this 2 data frames into the 'key column'
pd.merge(df1,df2,on="key",how="inner")  # In Pandas, Inner Join keeps only the rows that exist in both DataFrames based on the key column. So it returns the common matching rows.

  key  Values1  Values2
0   A        1        4
1   B        2        5

In [ ]:
pd.merge(df1, df2, on="key", how="outer") 
# In Pandas, Outer Join keeps all rows from both DataFrames.
# If a match is not found, the missing values are filled with NaN.

  key  Values1  Values2
0   A      1.0      4.0
1   B      2.0      5.0
2   C      3.0      NaN
3   D      NaN      6.0

In [ ]:
pd.merge(df1, df2, on="key", how="left")
# In Pandas, a Left Join keeps all rows from the left DataFrame and only the matching rows from the right DataFrame.
# If there is no match, the missing values become NaN.
# df1 → left table
# df2 → right table
# on="key" → column used for matching
# how="left" → keep all rows from df1

  key  Values1  Values2
0   A        1      4.0
1   B        2      5.0
2   C        3      NaN

In [ ]:
pd.merge(df1, df2, on="key", how="right")
# In Pandas, a Right Join keeps all rows from the right DataFrame and matches rows from the left DataFrame.
# If a match is not found in the left table, the missing values become NaN.

  key  Values1  Values2
0   A      1.0        4
1   B      2.0        5
2   D      NaN        6