## Pandas
Pandas is a powerful open-source Python library used for data manipulation and analysis. It allows users to easily work with structured data such as tables, similar to Excel or SQL databases. Pandas provides two main data structures: Series (1-dimensional data) and DataFrame (2-dimensional tabular data). With Pandas, you can read data from files like CSV or Excel, clean and preprocess datasets, filter and transform data, handle missing values, and perform statistical analysis. It is widely used in data analytics, data science, and machine learning, often together with libraries like NumPy for numerical operations and scikit-learn for building machine learning models.

In [4]:
import pandas as pd

print(pd.__version__)

3.0.1

## Series
In pandas, a Series is a one-dimensional labeled array that can store data of any type (integers, strings, floats, etc.). It is similar to a single column in a table or an Excel sheet, where each value has an index (label) and a corresponding data value. A Series helps in storing and manipulating a sequence of values efficiently and is built on top of NumPy arrays.

In [ ]:
#Creating a Simple Series
import pandas as pd

data = pd.Series([10, 20, 30, 40])
print(data)
# Here 0,1,2,3 are indexes and 10,20,30,40 are values.

0    10
1    20
2    30
3    40
dtype: int64

In [ ]:
# Series with Custom Index
import pandas as pd

data = pd.Series([90, 85, 88], index=["Math", "Science", "English"])
print(data)

# You can access values using the index:
print(data["Math"])  # it will print 90 since the "math" index stores 90

Math       90
Science    85
English    88
dtype: int64
90

In [ ]:
import pandas as pd
data = [10,20,30] # data of the series
index = ['a','b','c'] # indexes for the data 
pd.Series(data , index = index)

a    10
b    20
c    30
dtype: int64

In [8]:
# Series from Dictionary
import pandas as pd

data = {"A": 10, "B": 20, "C": 30}
s = pd.Series(data)

print(s)

A    10
B    20
C    30
dtype: int64

NOTE:- In short: A Series = Index + Values, representing one column of data in Pandas.

## DataFrame 
In pandas, a DataFrame is a two-dimensional labeled data structure that stores data in rows and columns, similar to a table in Excel or a database. Each column can contain different types of data such as numbers, strings, or dates. It is the most commonly used structure in Pandas for analyzing datasets. Internally, a DataFrame is built using NumPy arrays.

In [10]:
# Creating a DataFrame
import pandas as pd

data = {
    "Name": ["Abhishek", "Rahul", "Aman"],
    "Age": [21, 22, 23],
    "City": ["Delhi", "Mumbai", "Pune"]
}

df = pd.DataFrame(data)
print(df)

       Name  Age    City
0  Abhishek   21   Delhi
1     Rahul   22  Mumbai
2      Aman   23    Pune

In [11]:
# Accessing Data
df["Name"]      # access a column
df.iloc[0]      # access first row
df.head()       # first 5 rows

       Name  Age    City
0  Abhishek   21   Delhi
1     Rahul   22  Mumbai
2      Aman   23    Pune

In [ ]:
# converting the df(data frame) into a numpy array 
import numpy as np
np.array(df)

array([['Abhishek', 21, 'Delhi'],
       ['Rahul', 22, 'Mumbai'],
       ['Aman', 23, 'Pune']], dtype=object)

In [13]:
# In pandas, you can create a DataFrame from a list of dictionaries, where each dictionary represents one row and the keys become column names.
import pandas as pd

data = [
    {"Name": "Abhishek", "Age": 21, "City": "Delhi"},
    {"Name": "Rahul", "Age": 22, "City": "Mumbai"},
    {"Name": "Aman", "Age": 23, "City": "Pune"}
]

df = pd.DataFrame(data)

print(df)

       Name  Age    City
0  Abhishek   21   Delhi
1     Rahul   22  Mumbai
2      Aman   23    Pune

In [16]:
# read the data from the CSV file 
import pandas as pd

df = pd.read_csv("students.csv")

print(df)

       Name  Age            Course  Marks
0  Abhishek   21      Data Science     88
1     Rahul   22  Computer Science     75
2      Aman   20        Electrical     82
3     Priya   21        Mechanical     91
4     Sneha   22      Data Science     85

In [19]:
df.head()  # first 5 rows

       Name  Age            Course  Marks
0  Abhishek   21      Data Science     88
1     Rahul   22  Computer Science     75
2      Aman   20        Electrical     82
3     Priya   21        Mechanical     91
4     Sneha   22      Data Science     85

In [ ]:
df.head(2)  # first 2 rows

       Name  Age            Course  Marks
0  Abhishek   21      Data Science     88
1     Rahul   22  Computer Science     75

In [ ]:
df.info()  # gives info about the dataset

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      str
 1   Age     5 non-null      int64
 2   Course  5 non-null      str
 3   Marks   5 non-null      int64
dtypes: int64(2), str(2)
memory usage: 292.0 bytes

In [22]:
df

       Name  Age            Course  Marks
0  Abhishek   21      Data Science     88
1     Rahul   22  Computer Science     75
2      Aman   20        Electrical     82
3     Priya   21        Mechanical     91
4     Sneha   22      Data Science     85

In [ ]:
df['Name']  # accesing one col from the dataset

0    Abhishek
1       Rahul
2        Aman
3       Priya
4       Sneha
Name: Name, dtype: str

In [ ]:
df.loc[0]  # getting the row by row wise indexing ( for 0th row ) , here loc[] is the lock

Name          Abhishek
Age                 21
Course    Data Science
Marks               88
Name: 0, dtype: object

In [ ]:
df.iloc[0,0]   # 0th row and 0th col element (0,0) element  , iloc[] gives you the col index

'Abhishek'

In [ ]:
df["Name"] # selecting column
df[["Name", "Marks"]] # selecting multiple column
df.iloc[0]   # first row
df[df["Marks"] > 80] # filter the data
df["Grade"] = ["B", "C", "B", "A", "B"] # adding a new column
df.loc[0, "Marks"] = 90 # updating marks of the 0th row

In [ ]:
df.drop("Grade", axis=1, inplace=True)
# The axis parameter tells Pandas whether you want to drop a row or a column. axis=0 → drop rows or axis=1 → drop columns and inplace=True -> this tells Pandas to modify the original DataFrame directly. True → changes the original df and False → returns a new DataFrame without changing the original